### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-embed-api#1]
Because this API will power all iframe embeds the URL we choose must be final. It will also power oembeds but that endpoint is only for machines.

Since it will be very visible in the iframe `src` I'd prefer one word.

- https://embed.radio4000.com
- https://share.radio4000.com
- https://player.radio4000.com
- https://??.radio4000.com

**Comment by hellerve** [comment]
Personally, I am pro `embed`, because it makes the mission of the URL clear. The other two are a bit more muddy, meaning-wise, but that might just be my perception.

**Comment by hugurp** [comment]
let's go for `embed`, also agreeing with one word and mission of the url.

**Comment by hugurp** [comment]
So because this is a node app, we have to decide on the hosting.
+ now.sh: run 10 projects for 15/month https://zeit.co/pricing
+ heroku: pay per project, 7/month https://www.heroku.com/pricing
- can't be netlify.com, since they do only static websites

What we need:
- free + automatic SSL
- team account

What i wish for:
- automatic build + deploy on each project's `production` branch (like on netlify)

**Comment by oskarrough** [comment]
Agree! Let's go for team account on now.sh.

For automatic deploys we need to setup a CI service. Could be Travis?
